export const persons = [
  { id: '1', name: 'Rocky RRR', score: 25 },
  { id: '2', name: 'Soumya Patil ', score: 76 },
  { id: '3', name: 'Sachin T', score: 22 },
  { id: '4', name: 'Rohit S', score: 15 },
  { id: '5', name: 'Virat K', score: 75 },
  { id: '6', name: 'Saurav G', score: 65 },
  { id: '7', name: 'Grage C', score: 29 },
  { id: '8', name: 'Fleming S', score: 78 },
  { id: '9', name: 'Rohan T', score: 98 },
  { id: '10', name: 'Rahul Te', score: 25 },
  { id: '11', name: 'Vinod K', score: 89 },
  { id: '12', name: 'Irfan P', score: 19 },
  { id: '13', name: 'MO Kaif', score: 87 },
  { id: '14', name: 'Michel Stephan', score: 25 },
  { id: '15', name: 'Rohan Dutta', score: 90 },
  { id: '16', name: 'B Blake', score: 45 },
  { id: '17', name: 'R Ponting', score: 52 },
  { id: '18', name: 'Daiv Mi', score: 92 },
  { id: '19', name: 'Yunus P', score: 56 },
  { id: '20', name: 'John Alia', score: 85 },
];
